

services:
  app:
    build: .
    container_name: accountview-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    container_name: accountview-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountdb
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
