services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accountview-app-prod
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .env:/app/.env:ro  # Mount .env as read-only if it exists
    restart: unless-stopped
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0.39
    container_name: accountview-db-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: accountdb
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppassword}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "33307:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 30s

volumes:
  mysql-data-prod: